# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField()),
                ('app', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('action', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
                ('status', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=255)),
                ('list_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('pid', models.IntegerField()),
                ('status', models.IntegerField()),
                ('remark', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('list_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
