# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='app',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='menu',
            name='data',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='model',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
