# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20170601_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='list_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='action',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='list_order',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='app',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='data',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='model',
        ),
    ]
